auvic_msgs/protocol_deviceName_S TRIDENT_deviceName # Sent by: TRIDENT, Received by: No One
auvic_msgs/protocol_motorSetSpeed_S TRIDENT_motorSetSpeed # Sent by: TRIDENT, Received by: Motor Controller
auvic_msgs/protocol_powerEnable_S   TRIDENT_powerEnable # Sent by: TRIDENT, Received by: Power Board
auvic_msgs/protocol_PBMessageRequest_S TRIDENT_PBMessageRequest # Sent by: TRIDENT, Received by: Power Board 
auvic_msgs/protocol_MCMessageRequest_S TRIDENT_MCMessageRequest # Sent by TRIDENT, Received by: Motor Controller
auvic_msgs/protocol_ISOTP_S            TRIDENT_MCISOTP # Sent by TRIDENT, Received by: Motor Controller
auvic_msgs/protocol_deviceName_S    MC_deviceName # Sent by Motor Controller, Received by TRIDENT
auvic_msgs/protocol_motorRPM_S      MC_motorRPMLow # Sent by Motor Controller, Received by TRIDENT
auvic_msgs/protocol_motorRPM_S      MC_motorRPMHigh # Sent by Motor Controller, Received by TRIDENT
auvic_msgs/protocol_ISOTP_S         MC_ISOTP # Sent by Motor Controller, Received by TRIDENT
auvic_msgs/protocol_deviceName_S    PB_deviceName # Sent by Power Board, Received by TRIDENT
auvic_msgs/protocol_PBEnvData_S     PB_envData # Sent by Power Board, Received by TRIDENT
auvic_msgs/protocol_PBBattVoltages_S PB_battVoltages # Sent by Power Board, Received by TRIDENT
auvic_msgs/protocol_PBBattCurrents_S PB_battCurrents # Sent by Power Board, Received by TRIDENT










